const express = require('express');
const router = express.Router();
const { verifyToken } = require('../middleware/authMiddleware');
const { connectionController } = require('../controllers');
router.get('/', connectionController.getConnections);
router.post('/request', connectionController.sendConnectionRequest);
router.put('/:id/accept', connectionController.acceptConnectionRequest);
router.put('/:id/reject', connectionController.rejectConnectionRequest);
router.delete('/:id', connectionController.removeConnection);
router.get('/requests', connectionController.getConnectionRequests);
module.exports = router;
