const express = require('express');
const router = express.Router();
const { verifyToken } = require('../middleware/authMiddleware');
const { connectionController } = require('../controllers');
router.get('/', verifyToken, connectionController.getConnections);
router.post('/', verifyToken, connectionController.sendConnectionRequest);
router.put('/:id/accept', verifyToken, connectionController.acceptConnectionRequest);
router.put('/:id/reject', verifyToken, connectionController.rejectConnectionRequest);
router.delete('/:id', verifyToken, connectionController.removeConnection);
router.get('/requests', verifyToken, connectionController.getConnectionRequests);
module.exports = router;
